### PR TITLE
Add current speakers slide

### PR DESCRIPTION
**Pull request by paulfioravanti**

### CODE REVIEW

**Comment by paulfioravanti** [comment]
@tracymu Thanks for that.  I've made a couple more minor formatting changes, so bring them down into Deckset and check them out, and then if all's good, please merge, otherwise make any further changes you want and merge away :)

**Comment by tracymu** [comment]
@paulfioravanti 
I'm not super experienced with Deckset - but the `Tonight` and `Submit an Issue` slides - their text gets cut off for me?

**Comment by paulfioravanti** [comment]
Are you seeing the slides like this?

201709-rorosyd_md
201709-rorosyd_md

**Comment by tracymu** [comment]
Sorry, sorry, I was not at all seeing slides like this - Even now when I change to Franciska, I am seeing different colours

Sorry I mucked up your template, I should have left it alone

**Comment by paulfioravanti** [comment]
@tracymu Ah, yeah, there are multiple colour schemes per theme.  Up the top, it's specified as `theme: Franziska, 3`.  The colour schemes are indexed at 1, so it's the third colour scheme of the Franziska theme.  I figure that for each meetup, you can feel free to mix up the theme if you so desire :)

**Pull request merged**
